COMP: Update type correctness of point and vector math
This is necessitated by "ENH: Declare converting Point(v) constructors explicit" from Feb 28th:
https://github.com/InsightSoftwareConsortium/ITK/commit/8825834406356a66705437b74c843a54a47c57c3

The first error message was:

1>m:\dashboard\itk\modules\remote\montage\include\itkPhaseCorrelationImageRegistrationMethod.hxx(251): error C2440: 'initializing': cannot convert from 'itk::Vector<double,2>' to 'itk::Point<double,2>'
1>m:\dashboard\itk\modules\remote\montage\include\itkPhaseCorrelationImageRegistrationMethod.hxx(251): note: Constructor for class 'itk::Point<double,2>' is declared 'explicit'